### ISSUE TITLE
Remove use of pinv2 to make compatible with scipy 1.9

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [Argonne-National-Laboratory/FARM#12]
We will be updating RAVEN to a new version of scipy soon, and this line uses a function that is removed in scipy 1.9:

https://github.com/Argonne-National-Laboratory/FARM/blob/625b7e08d5c1489c892a0f427875f8fbf2a2944d/src/FARMValidatorsForHeron.py#L3068C14-L3068C32

I recommend switching it to [scipy.linalg.pinv](https://docs.scipy.org/doc/scipy-1.7.1/reference/reference/generated/scipy.linalg.pinv.html#scipy.linalg.pinv) instead.

Thanks

https://github.com/idaholab/raven/pull/2123

**Comment by wanghy-anl** [comment]
Thanks Joshua, it has been updated. I submitted a PR to update the FARM submodule.

**Comment by joshua-cogliati-inl** [comment]
@wanghy-anl Thank you for fixing this issue.
